package fi.chop.event;

public enum Events {
    ACTION_MERCY, ACTION_INTERACT, ACTION_BACK, ACTION_EXIT,
    EVT_GUILLOTINE_RAISE, EVT_GUILLOTINE_PREPARED, EVT_GUILLOTINE_RESTORED,
    EVT_PERSON_KILLED, EVT_PERSON_SAVED,
    EVT_REPUTATION_CHANGED, EVT_REPUTATION_LVL_CHANGED, EVT_POPULARITY_CHANGED,
    EVT_POWER_METER_STATE_CHANGED, EVT_GUILLOTINE_STATE_CHANGED
}
